apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka"  # This should be the external hostname of your Kafka brokers
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"  # This should match the advertised port
        - name: KAFKA_CREATE_TOPICS
          value: "topic1:1:1,topic2:1:1"  # Specify your desired topics and replication factor
        ports:
        - containerPort: 9092
          name: kafka
        volumeMounts:
        - name: data
          mountPath: /kafka/data
      - name: kafka-producer
        image: <your-golang-producer-image>
        command: ["./your-go-executable"]
        volumeMounts:
        - name: data
          mountPath: /kafka/data
      volumes:
      - name: data
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
